spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/district_db
spring.datasource.username=district_admin
spring.datasource.password=district_pswd
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topicName=ENLIST_STUDENT
spring.kafka.groupId=district-consumer-group